export const getAchievementDefinitionsES = (formatCurrency) => [
  {
    id: 'saved_1',
    title: 'Empieza el ahorro',
    description: `¡Has ahorrado ${formatCurrency(1)}!`,
    icon: '👛',
    requirement: 1,
    type: 'money',
  },
  {
    id: 'saved_10',
    title: '¡Ya van diez!',
    description: `¡Has ahorrado ${formatCurrency(10)}!`,
    icon: '📈',
    requirement: 10,
    type: 'money',
  },
  {
    id: 'units_1',
    title: 'Primer umbral superado',
    description: '¡Has evitado 1 unidad!',
    icon: '🥇',
    requirement: 1,
    type: 'units',
  },
  {
    id: 'days_1',
    title: 'Las primeras 24 horas',
    description: '¡Llevas 1 día sin alcohol!',
    icon: '1️⃣',
    requirement: 1,
    type: 'days',
  },
  {
    id: 'drinks_5',
    title: 'Cinco seguidas',
    description: '¡Has evitado 5 bebidas!',
    icon: '5️⃣',
    requirement: 5,
    type: 'drinks',
  },
  {
    id: 'saved_25',
    title: 'Ya cuenta de verdad',
    description: `¡Has ahorrado ${formatCurrency(25)}!`,
    icon: '💰',
    requirement: 25,
    type: 'money',
  },
  {
    id: 'days_2',
    title: 'No cediste',
    description: '¡Llevas 2 días sin alcohol!',
    icon: '🐫',
    requirement: 2,
    type: 'days',
  },
  {
    id: 'saved_50',
    title: 'La pila crece',
    description: `¡Has ahorrado ${formatCurrency(50)}!`,
    icon: '💸',
    requirement: 50,
    type: 'money',
  },
  {
    id: 'days_5',
    title: 'Ritmo encontrado',
    description: '¡Llevas 5 días sin alcohol!',
    icon: '🖐️',
    requirement: 5,
    type: 'days',
  },
  {
    id: 'saved_100',
    title: 'Esto suma en serio',
    description: `¡Has ahorrado ${formatCurrency(100)}!`,
    icon: '💰',
    requirement: 100,
    type: 'money',
  },
  {
    id: 'drinks_25',
    title: 'Lo estás haciendo genial',
    description: '¡Has evitado 25 bebidas!',
    icon: '💪',
    requirement: 25,
    type: 'drinks',
  },
  {
    id: 'units_10',
    title: 'Doble cifra',
    description: '¡Has evitado 10 unidades!',
    icon: '😏',
    requirement: 10,
    type: 'units',
  },
  {
    id: 'days_7',
    title: 'Primera semana completada',
    description: '¡Llevas 1 semana sin alcohol!',
    icon: '✅',
    requirement: 7,
    type: 'days',
  },
  {
    id: 'days_10',
    title: '¡Diez! ¡Diez! ¡Diez!',
    description: '¡Llevas 10 días sin alcohol!',
    icon: '🔟',
    requirement: 10,
    type: 'days',
  },
  {
    id: 'drinks_50',
    title: 'Qué gran hito',
    description: '¡Has evitado 50 bebidas!',
    icon: '🏆',
    requirement: 50,
    type: 'drinks',
  },
  {
    id: 'saved_250',
    title: 'La constancia paga',
    description: `¡Has ahorrado ${formatCurrency(250)}!`,
    icon: '🤑',
    requirement: 250,
    type: 'money',
  },
  {
    id: 'days_14',
    title: '¡Sí puedes!',
    description: '¡Llevas 2 semanas sin alcohol!',
    icon: '😎',
    requirement: 14,
    type: 'days',
  },
  {
    id: 'drinks_100',
    title: 'Cien de jefa o jefe',
    description: '¡Has evitado 100 bebidas!',
    icon: '💯',
    requirement: 100,
    type: 'drinks',
  },
  {
    id: 'days_21',
    title: 'Recuperando tu vida',
    description: '¡Llevas 3 semanas sin alcohol!',
    icon: '☀️',
    requirement: 21,
    type: 'days',
  },
  {
    id: 'saved_500',
    title: 'Imparable',
    description: `¡Has ahorrado ${formatCurrency(500)}!`,
    icon: '🛑',
    requirement: 500,
    type: 'money',
  },
  {
    id: 'units_50',
    title: '¡Eso es constancia!',
    description: '¡Has evitado 50 unidades!',
    icon: '👍',
    requirement: 50,
    type: 'units',
  },
  {
    id: 'days_30',
    title: 'Un mes al mando',
    description: '¡Llevas 1 mes sin alcohol!',
    icon: '🗓️',
    requirement: 30,
    type: 'days',
  },
  {
    id: 'drinks_200',
    title: 'Vas como un tren',
    description: '¡Has evitado 200 bebidas!',
    icon: '🚂',
    requirement: 200,
    type: 'drinks',
  },
  {
    id: 'days_42',
    title: 'Seis semanas de impulso',
    description: '¡Llevas 6 semanas sin alcohol!',
    icon: '😁',
    requirement: 42,
    type: 'days',
  },
  {
    id: 'saved_1000',
    title: 'Ya no son monedas',
    description: `¡Has ahorrado ${formatCurrency(1000)}!`,
    icon: '💶',
    requirement: 1000,
    type: 'money',
  },
  {
    id: 'units_100',
    title: '¡Estás ganando!',
    description: '¡Has evitado 100 unidades!',
    icon: '🏁',
    requirement: 100,
    type: 'units',
  },
  {
    id: 'drinks_300',
    title: 'Fuerza de hierro',
    description: '¡Has evitado 300 bebidas!',
    icon: '🧲',
    requirement: 300,
    type: 'drinks',
  },
  {
    id: 'days_60',
    title: 'No te rompes',
    description: '¡Llevas 2 meses sin alcohol!',
    icon: '🧱',
    requirement: 60,
    type: 'days',
  },
  {
    id: 'drinks_400',
    title: 'Siguiente nivel',
    description: '¡Has evitado 400 bebidas!',
    icon: '⏭️',
    requirement: 400,
    type: 'drinks',
  },
  {
    id: 'days_90',
    title: 'Deslizándote hacia adelante',
    description: '¡Llevas 3 meses sin alcohol!',
    icon: '🌊',
    requirement: 90,
    type: 'days',
  },
  {
    id: 'days_100',
    title: 'Otro gran paso',
    description: '¡Llevas 100 días sin alcohol!',
    icon: '💣',
    requirement: 100,
    type: 'days',
  },
  {
    id: 'drinks_500',
    title: 'En pie como una casa',
    description: '¡Has evitado 500 bebidas!',
    icon: '🏡',
    requirement: 500,
    type: 'drinks',
  },
  {
    id: 'saved_2500',
    title: 'Maestría financiera',
    description: `¡Has ahorrado ${formatCurrency(2500)}!`,
    icon: '💲',
    requirement: 2500,
    type: 'money',
  },
  {
    id: 'units_250',
    title: 'En llamas',
    description: '¡Has evitado 250 unidades!',
    icon: '🔥',
    requirement: 250,
    type: 'units',
  },
  {
    id: 'days_150',
    title: 'El tiempo juega contigo',
    description: '¡Llevas 150 días sin alcohol!',
    icon: '⌚',
    requirement: 150,
    type: 'days',
  },
  {
    id: 'days_180',
    title: 'Rey del medio año',
    description: '¡Llevas 6 meses sin alcohol!',
    icon: '👑',
    requirement: 180,
    type: 'days',
  },
  {
    id: 'drinks_1000',
    title: 'Éxito volcánico',
    description: '¡Has evitado 1000 bebidas!',
    icon: '🌋',
    requirement: 1000,
    type: 'drinks',
  },
  {
    id: 'days_250',
    title: 'Raíces profundas',
    description: '¡Llevas 250 días sin alcohol!',
    icon: '🌳',
    requirement: 250,
    type: 'days',
  },
  {
    id: 'saved_5000',
    title: 'Finanzas firmes',
    description: `¡Has ahorrado ${formatCurrency(5000)}!`,
    icon: '🏧',
    requirement: 5000,
    type: 'money',
  },
  {
    id: 'units_500',
    title: 'Balanza de disciplina',
    description: '¡Has evitado 500 unidades!',
    icon: '⚖️',
    requirement: 500,
    type: 'units',
  },
  {
    id: 'days_270',
    title: 'Renacido',
    description: '¡Llevas 9 meses sin alcohol!',
    icon: '👶',
    requirement: 270,
    type: 'days',
  },
  {
    id: 'days_365',
    title: 'Un año más allá',
    description: '¡Llevas 1 año sin alcohol!',
    icon: '🌟',
    requirement: 365,
    type: 'days',
  },
  {
    id: 'drinks_2000',
    title: 'La punta del iceberg',
    description: '¡Has evitado 2000 bebidas!',
    icon: '🗻',
    requirement: 2000,
    type: 'drinks',
  },
  {
    id: 'days_500',
    title: 'Explorador del camino',
    description: '¡Llevas 500 días sin alcohol!',
    icon: '🗺️',
    requirement: 500,
    type: 'days',
  },
  {
    id: 'saved_10000',
    title: '¡Vales oro!',
    description: `¡Has ahorrado ${formatCurrency(10000)}!`,
    icon: '🏆',
    requirement: 10000,
    type: 'money',
  },
  {
    id: 'units_1000',
    title: '¡1000 unidades!',
    description: '¡Has evitado 1000 unidades!',
    icon: '🏋️',
    requirement: 1000,
    type: 'units',
  },
  {
    id: 'days_730',
    title: 'Dos años: legendario',
    description: '¡Llevas 2 años sin alcohol!',
    icon: '🤩',
    requirement: 730,
    type: 'days',
  },
  {
    id: 'days_1000',
    title: 'Nivel 1000',
    description: '¡Llevas 1000 días sin alcohol!',
    icon: '🎮',
    requirement: 1000,
    type: 'days',
  },
  {
    id: 'drinks_5000',
    title: 'Árbol de perseverancia',
    description: '¡Has evitado 5000 bebidas!',
    icon: '🌳',
    requirement: 5000,
    type: 'drinks',
  },
  {
    id: 'days_1095',
    title: 'Tres años de claridad',
    description: '¡Llevas 3 años sin alcohol!',
    icon: '💡',
    requirement: 1095,
    type: 'days',
  },
  {
    id: 'saved_25000',
    title: 'Diamante tallado',
    description: `¡Has ahorrado ${formatCurrency(25000)}!`,
    icon: '💎',
    requirement: 25000,
    type: 'money',
  },
  {
    id: 'units_2500',
    title: '¡Brindis por ti!',
    description: '¡Has evitado 2500 unidades!',
    icon: '🥂',
    requirement: 2500,
    type: 'units',
  },
  {
    id: 'days_1825',
    title: '¿Qué era el alcohol?',
    description: '¡Llevas 5 años sin alcohol!',
    icon: '❓',
    requirement: 1825,
    type: 'days',
  },
  {
    id: 'drinks_10000',
    title: 'Nivel extraterrestre',
    description: '¡Has evitado 10.000 bebidas!',
    icon: '🛸',
    requirement: 10000,
    type: 'drinks',
  },
  {
    id: 'units_5000',
    title: 'Imparable total',
    description: '¡Has evitado 5000 unidades!',
    icon: '💪',
    requirement: 5000,
    type: 'units',
  },
  {
    id: 'units_7500',
    title: 'Estatus de estrella',
    description: '¡Has evitado 7500 unidades!',
    icon: '⭐️',
    requirement: 7500,
    type: 'units',
  },
  {
    id: 'units_10000',
    title: '¡Lo lograste!',
    description: '¡Has evitado 10.000 unidades!',
    icon: '🐐',
    requirement: 10000,
    type: 'units',
  },
];
