export const getAchievementDefinitionsNL = (formatCurrency) => [
  {
    id: 'saved_1',
    title: 'Het Sparen Begint',
    description: `Je hebt ${formatCurrency(1)} bespaard!`,
    icon: 'ðŸ‘›',
    requirement: 1,
    type: 'money',
  },
  {
    id: 'saved_10',
    title: 'Tientje Binnen!',
    description: `Je hebt ${formatCurrency(10)} bespaard!`,
    icon: 'ðŸ“ˆ',
    requirement: 10,
    type: 'money',
  },
  {
    id: 'units_1',
    title: 'Eerste Drempel Over',
    description: 'Je hebt 1 eenheid vermeden!',
    icon: 'ðŸ¥‡',
    requirement: 1,
    type: 'units',
  },
  {
    id: 'days_1',
    title: 'De Eerste 24 Uur',
    description: 'Je bent 1 dag ALCOHOL-vrij!',
    icon: '1ï¸âƒ£',
    requirement: 1,
    type: 'days',
  },
  {
    id: 'drinks_5',
    title: 'Vijf Op Een Rij',
    description: 'Je hebt 5 drankjes vermeden!',
    icon: '5ï¸âƒ£',
    requirement: 5,
    type: 'drinks',
  },
  {
    id: 'saved_25',
    title: 'Het Begint Te Tellen',
    description: `Je hebt ${formatCurrency(25)} bespaard!`,
    icon: 'ðŸ’°',
    requirement: 25,
    type: 'money',
  },
  {
    id: 'days_2',
    title: 'Niet Toegegeven',
    description: 'Je bent 2 dagen ALCOHOL-vrij!',
    icon: 'ðŸ«',
    requirement: 2,
    type: 'days',
  },
  {
    id: 'saved_50',
    title: 'De Stapel Groeit',
    description: `Je hebt ${formatCurrency(50)} bespaard!`,
    icon: 'ðŸ’¸',
    requirement: 50,
    type: 'money',
  },
  {
    id: 'days_5',
    title: 'Ritme Gevonden',
    description: 'Je bent 5 dagen ALCOHOL-vrij!',
    icon: 'ðŸ–ï¸',
    requirement: 5,
    type: 'days',
  },
  {
    id: 'saved_100',
    title: 'Dit Tikt Serieus Aan',
    description: `Je hebt ${formatCurrency(100)} bespaard!`,
    icon: 'ðŸ’°',
    requirement: 100,
    type: 'money',
  },
  {
    id: 'drinks_25',
    title: 'Lekker Bezig',
    description: 'Je hebt 25 drankjes vermeden!',
    icon: 'ðŸ’ª',
    requirement: 25,
    type: 'drinks',
  },
  {
    id: 'units_10',
    title: 'Dubbele Cijfers',
    description: 'Je hebt 10 eenheden vermeden!',
    icon: 'ðŸ˜',
    requirement: 10,
    type: 'units',
  },
  {
    id: 'days_7',
    title: 'Week EÃ©n Afgevinkt',
    description: 'Je bent 1 week ALCOHOL-vrij!',
    icon: 'âœ…',
    requirement: 7,
    type: 'days',
  },
  {
    id: 'days_10',
    title: 'Tien! Tien! Tien!',
    description: 'Je bent 10 dagen ALCOHOL-vrij!',
    icon: 'ðŸ”Ÿ',
    requirement: 10,
    type: 'days',
  },
  {
    id: 'drinks_50',
    title: 'Wat Een Mijlpaal',
    description: 'Je hebt 50 drankjes vermeden!',
    icon: 'ðŸ†',
    requirement: 50,
    type: 'drinks',
  },
  {
    id: 'saved_250',
    title: 'Volhouden Loont',
    description: `Je hebt ${formatCurrency(250)} bespaard!`,
    icon: 'ðŸ¤‘',
    requirement: 250,
    type: 'money',
  },
  {
    id: 'days_14',
    title: 'Je Kunt Dit!',
    description: 'Je bent 2 weken ALCOHOL-vrij!',
    icon: 'ðŸ˜Ž',
    requirement: 14,
    type: 'days',
  },
  {
    id: 'drinks_100',
    title: 'Honderd Keer De Baas',
    description: 'Je hebt 100 drankjes vermeden!',
    icon: 'ðŸ’¯',
    requirement: 100,
    type: 'drinks',
  },
  {
    id: 'days_21',
    title: 'Je Pakt Je Leven Terug',
    description: 'Je bent 3 weken ALCOHOL-vrij!',
    icon: 'â˜€ï¸',
    requirement: 21,
    type: 'days',
  },
  {
    id: 'saved_500',
    title: 'Je Bent Niet Te Stoppen',
    description: `Je hebt ${formatCurrency(500)} bespaard!`,
    icon: 'ðŸ›‘',
    requirement: 500,
    type: 'money',
  },
  {
    id: 'units_50',
    title: 'Dit Is Consistentie!',
    description: 'Je hebt 50 eenheden vermeden!',
    icon: 'ðŸ‘',
    requirement: 50,
    type: 'units',
  },
  {
    id: 'days_30',
    title: 'Een Maand In Controle',
    description: 'Je bent een maand ALCOHOL-vrij!',
    icon: 'ðŸ—“ï¸',
    requirement: 30,
    type: 'days',
  },
  {
    id: 'drinks_200',
    title: 'Je Gaat Als Een Trein',
    description: 'Je hebt 200 drankjes vermeden!',
    icon: 'ðŸš‚',
    requirement: 200,
    type: 'drinks',
  },
  {
    id: 'days_42',
    title: 'Zes Weken Momentum',
    description: 'Je bent 6 weken ALCOHOL-vrij!',
    icon: 'ðŸ˜',
    requirement: 42,
    type: 'days',
  },
  {
    id: 'saved_1000',
    title: 'Dit Is Geen Kleingeld Meer',
    description: `Je hebt ${formatCurrency(1000)} bespaard!`,
    icon: 'ðŸ’¶',
    requirement: 1000,
    type: 'money',
  },
  {
    id: 'units_100',
    title: 'Je Bent Aan Het Winnen!',
    description: 'Je hebt 100 eenheden vermeden!',
    icon: 'ðŸ',
    requirement: 100,
    type: 'units',
  },
  {
    id: 'drinks_300',
    title: 'Ijzersterk',
    description: 'Je hebt 300 drankjes vermeden!',
    icon: 'ðŸ§²',
    requirement: 300,
    type: 'drinks',
  },
  {
    id: 'days_60',
    title: 'Je Bent Niet Te Breken',
    description: 'Je bent 2 maanden ALCOHOL-vrij!',
    icon: 'ðŸ§±',
    requirement: 60,
    type: 'days',
  },
  {
    id: 'drinks_400',
    title: 'Next Level',
    description: 'Je hebt 400 drankjes vermeden!',
    icon: 'â­ï¸',
    requirement: 400,
    type: 'drinks',
  },
  {
    id: 'days_90',
    title: 'Je Surft Door',
    description: 'Je bent 3 maanden ALCOHOL-vrij!',
    icon: 'ðŸŒŠ',
    requirement: 90,
    type: 'days',
  },
  {
    id: 'days_100',
    title: 'Bam, Weer Een Stap',
    description: 'Je bent 100 dagen ALCOHOL-vrij!',
    icon: 'ðŸ’£',
    requirement: 100,
    type: 'days',
  },
  {
    id: 'drinks_500',
    title: 'Je Staat Als Een Huis',
    description: 'Je hebt 500 drankjes vermeden!',
    icon: 'ðŸ¡',
    requirement: 500,
    type: 'drinks',
  },
  {
    id: 'saved_2500',
    title: 'FinanciÃ«le Master',
    description: `Je hebt ${formatCurrency(2500)} bespaard!`,
    icon: 'ðŸ’²',
    requirement: 2500,
    type: 'money',
  },
  {
    id: 'units_250',
    title: 'On Fire',
    description: 'Je hebt 250 eenheden vermeden!',
    icon: 'ðŸ”¥',
    requirement: 250,
    type: 'units',
  },
  {
    id: 'days_150',
    title: 'Tijd Werkt Voor Jou',
    description: 'Je bent 150 dagen ALCOHOL-vrij!',
    icon: 'âŒš',
    requirement: 150,
    type: 'days',
  },
  {
    id: 'days_180',
    title: 'Halfjaar Koning',
    description: 'Je bent 6 maanden ALCOHOL-vrij!',
    icon: 'ðŸ‘‘',
    requirement: 180,
    type: 'days',
  },
  {
    id: 'drinks_1000',
    title: 'Vulkanisch Succes',
    description: 'Je hebt 1000 drankjes vermeden!',
    icon: 'ðŸŒ‹',
    requirement: 1000,
    type: 'drinks',
  },
  {
    id: 'days_250',
    title: 'Diepe Wortels',
    description: 'Je bent 250 dagen ALCOHOL-vrij!',
    icon: 'ðŸŒ³',
    requirement: 250,
    type: 'days',
  },
  {
    id: 'saved_5000',
    title: 'Financieel Stevig',
    description: `Je hebt ${formatCurrency(5000)} bespaard!`,
    icon: 'ðŸ§',
    requirement: 5000,
    type: 'money',
  },
  {
    id: 'units_500',
    title: 'Weegschaal van Discipline',
    description: 'Je hebt 500 eenheden vermeden!',
    icon: 'âš–ï¸',
    requirement: 500,
    type: 'units',
  },
  {
    id: 'days_270',
    title: 'Herboren',
    description: 'Je bent 9 maanden ALCOHOL-vrij!',
    icon: 'ðŸ‘¶',
    requirement: 270,
    type: 'days',
  },
  {
    id: 'days_365',
    title: 'Een Jaar Verder',
    description: 'Je bent 1 jaar ALCOHOL-vrij!',
    icon: 'ðŸŒŸ',
    requirement: 365,
    type: 'days',
  },
  {
    id: 'drinks_2000',
    title: 'Topje van de Ijsberg',
    description: 'Je hebt 2000 drankjes vermeden!',
    icon: 'ðŸ—»',
    requirement: 2000,
    type: 'drinks',
  },
  {
    id: 'days_500',
    title: 'Padvinder',
    description: 'Je bent 500 dagen ALCOHOL-vrij!',
    icon: 'ðŸ—ºï¸',
    requirement: 500,
    type: 'days',
  },
  {
    id: 'saved_10000',
    title: 'Jij Bent Goud Waard!',
    description: `Je hebt ${formatCurrency(10000)} bespaard!`,
    icon: 'ðŸ†',
    requirement: 10000,
    type: 'money',
  },
  {
    id: 'units_1000',
    title: '1000 Eenheden!',
    description: 'Je hebt 1000 eenheden vermeden!',
    icon: 'ðŸ‹ï¸',
    requirement: 1000,
    type: 'units',
  },
  {
    id: 'days_730',
    title: 'Twee Jaar: Legendarisch',
    description: 'Je bent 2 jaar ALCOHOL-vrij!',
    icon: 'ðŸ¤©',
    requirement: 730,
    type: 'days',
  },
  {
    id: 'days_1000',
    title: 'Level 1000',
    description: 'Je bent 1000 dagen ALCOHOL-vrij!',
    icon: 'ðŸŽ®',
    requirement: 1000,
    type: 'days',
  },
  {
    id: 'drinks_5000',
    title: 'De Boom van Doorzetting',
    description: 'Je hebt 5.000 drankjes vermeden!',
    icon: 'ðŸŒ³',
    requirement: 5000,
    type: 'drinks',
  },
  {
    id: 'days_1095',
    title: 'Drie Jaar Lichtpunt',
    description: 'Je bent 3 jaar ALCOHOL-vrij!',
    icon: 'ðŸ’¡',
    requirement: 1095,
    type: 'days',
  },
  {
    id: 'saved_25000',
    title: 'Geslepen Diamant',
    description: `Je hebt ${formatCurrency(25000)} bespaard!`,
    icon: 'ðŸ’Ž',
    requirement: 25000,
    type: 'money',
  },
  {
    id: 'units_2500',
    title: 'Proost op Jou!',
    description: 'Je hebt 2500 eenheden vermeden!',
    icon: 'ðŸ¥‚',
    requirement: 2500,
    type: 'units',
  },
  {
    id: 'days_1825',
    title: 'Wat Is ALCOHOL?',
    description: 'Je bent 5 jaar ALCOHOL-vrij!',
    icon: 'â“',
    requirement: 1825,
    type: 'days',
  },
  {
    id: 'drinks_10000',
    title: 'Buitenaards Niveau',
    description: 'Je hebt 10.000 drankjes vermeden!',
    icon: 'ðŸ›¸',
    requirement: 10000,
    type: 'drinks',
  },
  {
    id: 'units_5000',
    title: 'Onstuitbaar',
    description: 'Je hebt 5000 eenheden vermeden!',
    icon: 'ðŸ’ª',
    requirement: 5000,
    type: 'units',
  },
  {
    id: 'units_7500',
    title: 'Sterrenstatus',
    description: 'Je hebt 7500 eenheden vermeden!',
    icon: 'â­ï¸',
    requirement: 7500,
    type: 'units',
  },
  {
    id: 'units_10000',
    title: 'Je hebt het uitgespeeld!',
    description: 'Je hebt 10.000 eenheden vermeden!',
    icon: 'ðŸ',
    requirement: 10000,
    type: 'units',
  },
];

export const getAchievementDefinitionsEN = (formatCurrency) => [
  {
    id: 'saved_1',
    title: 'Savings Begin',
    description: `You saved ${formatCurrency(1)}!`,
    icon: 'ðŸ‘›',
    requirement: 1,
    type: 'money',
  },
  {
    id: 'saved_10',
    title: 'Ten In!',
    description: `You saved ${formatCurrency(10)}!`,
    icon: 'ðŸ“ˆ',
    requirement: 10,
    type: 'money',
  },
  {
    id: 'units_1',
    title: 'First Threshold Crossed',
    description: 'You avoided 1 unit!',
    icon: 'ðŸ¥‡',
    requirement: 1,
    type: 'units',
  },
  {
    id: 'days_1',
    title: 'The First 24 Hours',
    description: 'You are 1 day ALCOHOL-free!',
    icon: '1ï¸âƒ£',
    requirement: 1,
    type: 'days',
  },
  {
    id: 'drinks_5',
    title: 'Five In A Row',
    description: 'You avoided 5 drinks!',
    icon: '5ï¸âƒ£',
    requirement: 5,
    type: 'drinks',
  },
  {
    id: 'saved_25',
    title: 'It Starts To Count',
    description: `You saved ${formatCurrency(25)}!`,
    icon: 'ðŸ’°',
    requirement: 25,
    type: 'money',
  },
  {
    id: 'days_2',
    title: 'Did Not Give In',
    description: 'You are 2 days ALCOHOL-free!',
    icon: 'ðŸ«',
    requirement: 2,
    type: 'days',
  },
  {
    id: 'saved_50',
    title: 'The Stack Grows',
    description: `You saved ${formatCurrency(50)}!`,
    icon: 'ðŸ’¸',
    requirement: 50,
    type: 'money',
  },
  {
    id: 'days_5',
    title: 'Found Rhythm',
    description: 'You are 5 days ALCOHOL-free!',
    icon: 'ðŸ–ï¸',
    requirement: 5,
    type: 'days',
  },
  {
    id: 'saved_100',
    title: 'This Adds Up Seriously',
    description: `You saved ${formatCurrency(100)}!`,
    icon: 'ðŸ’°',
    requirement: 100,
    type: 'money',
  },
  {
    id: 'drinks_25',
    title: 'Doing Great',
    description: 'You avoided 25 drinks!',
    icon: 'ðŸ’ª',
    requirement: 25,
    type: 'drinks',
  },
  {
    id: 'units_10',
    title: 'Double Digits',
    description: 'You avoided 10 units!',
    icon: 'ðŸ˜',
    requirement: 10,
    type: 'units',
  },
  {
    id: 'days_7',
    title: 'Week One Checked Off',
    description: 'You are 1 week ALCOHOL-free!',
    icon: 'âœ…',
    requirement: 7,
    type: 'days',
  },
  {
    id: 'days_10',
    title: 'Ten! Ten! Ten!',
    description: 'You are 10 days ALCOHOL-free!',
    icon: 'ðŸ”Ÿ',
    requirement: 10,
    type: 'days',
  },
  {
    id: 'drinks_50',
    title: 'What A Milestone',
    description: 'You avoided 50 drinks!',
    icon: 'ðŸ†',
    requirement: 50,
    type: 'drinks',
  },
  {
    id: 'saved_250',
    title: 'Persistence Pays',
    description: `You saved ${formatCurrency(250)}!`,
    icon: 'ðŸ¤‘',
    requirement: 250,
    type: 'money',
  },
  {
    id: 'days_14',
    title: 'You Can Do This!',
    description: 'You are 2 weeks ALCOHOL-free!',
    icon: 'ðŸ˜Ž',
    requirement: 14,
    type: 'days',
  },
  {
    id: 'drinks_100',
    title: 'Boss Hundred Times',
    description: 'You avoided 100 drinks!',
    icon: 'ðŸ’¯',
    requirement: 100,
    type: 'drinks',
  },
  {
    id: 'days_21',
    title: 'Taking Your Life Back',
    description: 'You are 3 weeks ALCOHOL-free!',
    icon: 'â˜€ï¸',
    requirement: 21,
    type: 'days',
  },
  {
    id: 'saved_500',
    title: 'You Cannot Be Stopped',
    description: `You saved ${formatCurrency(500)}!`,
    icon: 'ðŸ›‘',
    requirement: 500,
    type: 'money',
  },
  {
    id: 'units_50',
    title: 'This Is Consistency!',
    description: 'You avoided 50 units!',
    icon: 'ðŸ‘',
    requirement: 50,
    type: 'units',
  },
  {
    id: 'days_30',
    title: 'A Month In Control',
    description: 'You are 1 month ALCOHOL-free!',
    icon: 'ðŸ—“ï¸',
    requirement: 30,
    type: 'days',
  },
  {
    id: 'drinks_200',
    title: 'Going Like A Train',
    description: 'You avoided 200 drinks!',
    icon: 'ðŸš‚',
    requirement: 200,
    type: 'drinks',
  },
  {
    id: 'days_42',
    title: 'Six Weeks Momentum',
    description: 'You are 6 weeks ALCOHOL-free!',
    icon: 'ðŸ˜',
    requirement: 42,
    type: 'days',
  },
  {
    id: 'saved_1000',
    title: 'Not Small Change Anymore',
    description: `You saved ${formatCurrency(1000)}!`,
    icon: 'ðŸ’¶',
    requirement: 1000,
    type: 'money',
  },
  {
    id: 'units_100',
    title: 'You Are Winning!',
    description: 'You avoided 100 units!',
    icon: 'ðŸ',
    requirement: 100,
    type: 'units',
  },
  {
    id: 'drinks_300',
    title: 'Iron Strong',
    description: 'You avoided 300 drinks!',
    icon: 'ðŸ§²',
    requirement: 300,
    type: 'drinks',
  },
  {
    id: 'days_60',
    title: 'You Cannot Be Broken',
    description: 'You are 2 months ALCOHOL-free!',
    icon: 'ðŸ§±',
    requirement: 60,
    type: 'days',
  },
  {
    id: 'drinks_400',
    title: 'Next Level',
    description: 'You avoided 400 drinks!',
    icon: 'â­ï¸',
    requirement: 400,
    type: 'drinks',
  },
  {
    id: 'days_90',
    title: 'Surfing Through',
    description: 'You are 3 months ALCOHOL-free!',
    icon: 'ðŸŒŠ',
    requirement: 90,
    type: 'days',
  },
  {
    id: 'days_100',
    title: 'Bam, Another Step',
    description: 'You are 100 days ALCOHOL-free!',
    icon: 'ðŸ’£',
    requirement: 100,
    type: 'days',
  },
  {
    id: 'drinks_500',
    title: 'You Stand Like A House',
    description: 'You avoided 500 drinks!',
    icon: 'ðŸ¡',
    requirement: 500,
    type: 'drinks',
  },
  {
    id: 'saved_2500',
    title: 'Financial Master',
    description: `You saved ${formatCurrency(2500)}!`,
    icon: 'ðŸ’²',
    requirement: 2500,
    type: 'money',
  },
  {
    id: 'units_250',
    title: 'On Fire',
    description: 'You avoided 250 units!',
    icon: 'ðŸ”¥',
    requirement: 250,
    type: 'units',
  },
  {
    id: 'days_150',
    title: 'Time Works For You',
    description: 'You are 150 days ALCOHOL-free!',
    icon: 'âŒš',
    requirement: 150,
    type: 'days',
  },
  {
    id: 'days_180',
    title: 'Half Year King',
    description: 'You are 6 months ALCOHOL-free!',
    icon: 'ðŸ‘‘',
    requirement: 180,
    type: 'days',
  },
  {
    id: 'drinks_1000',
    title: 'Volcanic Success',
    description: 'You avoided 1000 drinks!',
    icon: 'ðŸŒ‹',
    requirement: 1000,
    type: 'drinks',
  },
  {
    id: 'days_250',
    title: 'Deep Roots',
    description: 'You are 250 days ALCOHOL-free!',
    icon: 'ðŸŒ³',
    requirement: 250,
    type: 'days',
  },
  {
    id: 'saved_5000',
    title: 'Financially Solid',
    description: `You saved ${formatCurrency(5000)}!`,
    icon: 'ðŸ§',
    requirement: 5000,
    type: 'money',
  },
  {
    id: 'units_500',
    title: 'Scale of Discipline',
    description: 'You avoided 500 units!',
    icon: 'âš–ï¸',
    requirement: 500,
    type: 'units',
  },
  {
    id: 'days_270',
    title: 'Reborn',
    description: 'You are 9 months ALCOHOL-free!',
    icon: 'ðŸ‘¶',
    requirement: 270,
    type: 'days',
  },
  {
    id: 'days_365',
    title: 'A Year Forward',
    description: 'You are 1 year ALCOHOL-free!',
    icon: 'ðŸŒŸ',
    requirement: 365,
    type: 'days',
  },
  {
    id: 'drinks_2000',
    title: 'Tip Of The Iceberg',
    description: 'You avoided 2000 drinks!',
    icon: 'ðŸ—»',
    requirement: 2000,
    type: 'drinks',
  },
  {
    id: 'days_500',
    title: 'Pathfinder',
    description: 'You are 500 days ALCOHOL-free!',
    icon: 'ðŸ—ºï¸',
    requirement: 500,
    type: 'days',
  },
  {
    id: 'saved_10000',
    title: 'You Are Worth Gold!',
    description: `You saved ${formatCurrency(10000)}!`,
    icon: 'ðŸ†',
    requirement: 10000,
    type: 'money',
  },
  {
    id: 'units_1000',
    title: '1000 Units!',
    description: 'You avoided 1000 units!',
    icon: 'ðŸ‹ï¸',
    requirement: 1000,
    type: 'units',
  },
  {
    id: 'days_730',
    title: 'Two Years: Legendary',
    description: 'You are 2 years ALCOHOL-free!',
    icon: 'ðŸ¤©',
    requirement: 730,
    type: 'days',
  },
  {
    id: 'days_1000',
    title: 'Level 1000',
    description: 'You are 1000 days ALCOHOL-free!',
    icon: 'ðŸŽ®',
    requirement: 1000,
    type: 'days',
  },
  {
    id: 'drinks_5000',
    title: 'Tree Of Perseverance',
    description: 'You avoided 5,000 drinks!',
    icon: 'ðŸŒ³',
    requirement: 5000,
    type: 'drinks',
  },
  {
    id: 'days_1095',
    title: 'Three Year Bright Spot',
    description: 'You are 3 years ALCOHOL-free!',
    icon: 'ðŸ’¡',
    requirement: 1095,
    type: 'days',
  },
  {
    id: 'saved_25000',
    title: 'Cut Diamond',
    description: `You saved ${formatCurrency(25000)}!`,
    icon: 'ðŸ’Ž',
    requirement: 25000,
    type: 'money',
  },
  {
    id: 'units_2500',
    title: 'Cheers To You!',
    description: 'You avoided 2500 units!',
    icon: 'ðŸ¥‚',
    requirement: 2500,
    type: 'units',
  },
  {
    id: 'days_1825',
    title: 'What Is ALCOHOL?',
    description: 'You are 5 years ALCOHOL-free!',
    icon: 'â“',
    requirement: 1825,
    type: 'days',
  },
  {
    id: 'drinks_10000',
    title: 'Alien Level',
    description: 'You avoided 10,000 drinks!',
    icon: 'ðŸ›¸',
    requirement: 10000,
    type: 'drinks',
  },
  {
    id: 'units_5000',
    title: 'Unstoppable',
    description: 'You avoided 5000 units!',
    icon: 'ðŸ’ª',
    requirement: 5000,
    type: 'units',
  },
  {
    id: 'units_7500',
    title: 'Star Status',
    description: 'You avoided 7500 units!',
    icon: 'â­ï¸',
    requirement: 7500,
    type: 'units',
  },
  {
    id: 'units_10000',
    title: 'You Nailed It!',
    description: 'You avoided 10,000 units!',
    icon: 'ðŸ',
    requirement: 10000,
    type: 'units',
  },
];
export const getAchievementDefinitionsFR = (formatCurrency) => [
  {
    id: 'saved_1',
    title: 'Les Ã©conomies commencent',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(1)} !`,
    icon: 'ðŸ‘›',
    requirement: 1,
    type: 'money',
  },
  {
    id: 'saved_10',
    title: 'Dix en poche !',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(10)} !`,
    icon: 'ðŸ“ˆ',
    requirement: 10,
    type: 'money',
  },
  {
    id: 'units_1',
    title: 'Premier cap franchi',
    description: 'Tu as Ã©vitÃ© 1 unitÃ© !',
    icon: 'ðŸ¥‡',
    requirement: 1,
    type: 'units',
  },
  {
    id: 'days_1',
    title: 'Les premiÃ¨res 24 heures',
    description: 'Tu es sobre depuis 1 jour !',
    icon: '1ï¸âƒ£',
    requirement: 1,
    type: 'days',
  },
  {
    id: 'drinks_5',
    title: 'Cinq dâ€™affilÃ©e',
    description: 'Tu as Ã©vitÃ© 5 verres !',
    icon: '5ï¸âƒ£',
    requirement: 5,
    type: 'drinks',
  },
  {
    id: 'saved_25',
    title: 'Ã‡a commence Ã  compter',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(25)} !`,
    icon: 'ðŸ’°',
    requirement: 25,
    type: 'money',
  },
  {
    id: 'days_2',
    title: 'Tu nâ€™as pas cÃ©dÃ©',
    description: 'Tu es sobre depuis 2 jours !',
    icon: 'ðŸ«',
    requirement: 2,
    type: 'days',
  },
  {
    id: 'saved_50',
    title: 'La pile grandit',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(50)} !`,
    icon: 'ðŸ’¸',
    requirement: 50,
    type: 'money',
  },
  {
    id: 'days_5',
    title: 'Le rythme est lÃ ',
    description: 'Tu es sobre depuis 5 jours !',
    icon: 'ðŸ–ï¸',
    requirement: 5,
    type: 'days',
  },
  {
    id: 'saved_100',
    title: 'Ã‡a devient sÃ©rieux',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(100)} !`,
    icon: 'ðŸ’°',
    requirement: 100,
    type: 'money',
  },
  {
    id: 'drinks_25',
    title: 'Tu gÃ¨res',
    description: 'Tu as Ã©vitÃ© 25 verres !',
    icon: 'ðŸ’ª',
    requirement: 25,
    type: 'drinks',
  },
  {
    id: 'units_10',
    title: 'Double chiffre',
    description: 'Tu as Ã©vitÃ© 10 unitÃ©s !',
    icon: 'ðŸ˜',
    requirement: 10,
    type: 'units',
  },
  {
    id: 'days_7',
    title: 'PremiÃ¨re semaine validÃ©e',
    description: 'Tu es sobre depuis 1 semaine !',
    icon: 'âœ…',
    requirement: 7,
    type: 'days',
  },
  {
    id: 'days_10',
    title: 'Dix jours !',
    description: 'Tu es sobre depuis 10 jours !',
    icon: 'ðŸ”Ÿ',
    requirement: 10,
    type: 'days',
  },
  {
    id: 'drinks_50',
    title: 'Quel cap !',
    description: 'Tu as Ã©vitÃ© 50 verres !',
    icon: 'ðŸ†',
    requirement: 50,
    type: 'drinks',
  },
  {
    id: 'saved_250',
    title: 'La persÃ©vÃ©rance paie',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(250)} !`,
    icon: 'ðŸ¤‘',
    requirement: 250,
    type: 'money',
  },
  {
    id: 'days_14',
    title: 'Tu peux le faire !',
    description: 'Tu es sobre depuis 2 semaines !',
    icon: 'ðŸ˜Ž',
    requirement: 14,
    type: 'days',
  },
  {
    id: 'drinks_100',
    title: 'Cent fois maÃ®tre',
    description: 'Tu as Ã©vitÃ© 100 verres !',
    icon: 'ðŸ’¯',
    requirement: 100,
    type: 'drinks',
  },
  {
    id: 'days_21',
    title: 'Tu reprends ta vie',
    description: 'Tu es sobre depuis 3 semaines !',
    icon: 'â˜€ï¸',
    requirement: 21,
    type: 'days',
  },
  {
    id: 'saved_500',
    title: 'InarrÃªtable',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(500)} !`,
    icon: 'ðŸ›‘',
    requirement: 500,
    type: 'money',
  },
  {
    id: 'units_50',
    title: 'Pure constance',
    description: 'Tu as Ã©vitÃ© 50 unitÃ©s !',
    icon: 'ðŸ‘',
    requirement: 50,
    type: 'units',
  },
  {
    id: 'days_30',
    title: 'Un mois de contrÃ´le',
    description: 'Tu es sobre depuis 1 mois !',
    icon: 'ðŸ—“ï¸',
    requirement: 30,
    type: 'days',
  },

  {
    id: 'drinks_200',
    title: 'Tu avances comme un train',
    description: 'Tu as Ã©vitÃ© 200 verres !',
    icon: 'ðŸš‚',
    requirement: 200,
    type: 'drinks',
  },
  {
    id: 'days_42',
    title: 'Six semaines de momentum',
    description: 'Tu es sobre depuis 6 semaines !',
    icon: 'ðŸ˜',
    requirement: 42,
    type: 'days',
  },
  {
    id: 'saved_1000',
    title: 'Ce nâ€™est plus de la petite monnaie',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(1000)} !`,
    icon: 'ðŸ’¶',
    requirement: 1000,
    type: 'money',
  },
  {
    id: 'units_100',
    title: 'Tu es en train de gagner !',
    description: 'Tu as Ã©vitÃ© 100 unitÃ©s !',
    icon: 'ðŸ',
    requirement: 100,
    type: 'units',
  },
  {
    id: 'drinks_300',
    title: 'Solide comme lâ€™acier',
    description: 'Tu as Ã©vitÃ© 300 verres !',
    icon: 'ðŸ§²',
    requirement: 300,
    type: 'drinks',
  },
  {
    id: 'days_60',
    title: 'Impossible Ã  briser',
    description: 'Tu es sobre depuis 2 mois !',
    icon: 'ðŸ§±',
    requirement: 60,
    type: 'days',
  },
  {
    id: 'drinks_400',
    title: 'Niveau supÃ©rieur',
    description: 'Tu as Ã©vitÃ© 400 verres !',
    icon: 'â­ï¸',
    requirement: 400,
    type: 'drinks',
  },
  {
    id: 'days_90',
    title: 'Tu surfes dessus',
    description: 'Tu es sobre depuis 3 mois !',
    icon: 'ðŸŒŠ',
    requirement: 90,
    type: 'days',
  },
  {
    id: 'days_100',
    title: 'Bam, encore un cap',
    description: 'Tu es sobre depuis 100 jours !',
    icon: 'ðŸ’£',
    requirement: 100,
    type: 'days',
  },
  {
    id: 'drinks_500',
    title: 'Solide comme une maison',
    description: 'Tu as Ã©vitÃ© 500 verres !',
    icon: 'ðŸ¡',
    requirement: 500,
    type: 'drinks',
  },
  {
    id: 'saved_2500',
    title: 'MaÃ®tre financier',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(2500)} !`,
    icon: 'ðŸ’²',
    requirement: 2500,
    type: 'money',
  },
  {
    id: 'units_250',
    title: 'En feu',
    description: 'Tu as Ã©vitÃ© 250 unitÃ©s !',
    icon: 'ðŸ”¥',
    requirement: 250,
    type: 'units',
  },
  {
    id: 'days_150',
    title: 'Le temps joue pour toi',
    description: 'Tu es sobre depuis 150 jours !',
    icon: 'âŒš',
    requirement: 150,
    type: 'days',
  },
  {
    id: 'days_180',
    title: 'Roi du semestre',
    description: 'Tu es sobre depuis 6 mois !',
    icon: 'ðŸ‘‘',
    requirement: 180,
    type: 'days',
  },
  {
    id: 'drinks_1000',
    title: 'SuccÃ¨s volcanique',
    description: 'Tu as Ã©vitÃ© 1000 verres !',
    icon: 'ðŸŒ‹',
    requirement: 1000,
    type: 'drinks',
  },
  {
    id: 'days_250',
    title: 'Racines profondes',
    description: 'Tu es sobre depuis 250 jours !',
    icon: 'ðŸŒ³',
    requirement: 250,
    type: 'days',
  },
  {
    id: 'saved_5000',
    title: 'Solide financiÃ¨rement',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(5000)} !`,
    icon: 'ðŸ§',
    requirement: 5000,
    type: 'money',
  },
  {
    id: 'units_500',
    title: 'Balance de discipline',
    description: 'Tu as Ã©vitÃ© 500 unitÃ©s !',
    icon: 'âš–ï¸',
    requirement: 500,
    type: 'units',
  },
  {
    id: 'days_270',
    title: 'Re-nÃ©',
    description: 'Tu es sobre depuis 9 mois !',
    icon: 'ðŸ‘¶',
    requirement: 270,
    type: 'days',
  },
  {
    id: 'days_365',
    title: 'Un an plus tard',
    description: 'Tu es sobre depuis 1 an !',
    icon: 'ðŸŒŸ',
    requirement: 365,
    type: 'days',
  },
  {
    id: 'drinks_2000',
    title: 'La partie Ã©mergÃ©e',
    description: 'Tu as Ã©vitÃ© 2000 verres !',
    icon: 'ðŸ—»',
    requirement: 2000,
    type: 'drinks',
  },
  {
    id: 'days_500',
    title: 'Explorateur du chemin',
    description: 'Tu es sobre depuis 500 jours !',
    icon: 'ðŸ—ºï¸',
    requirement: 500,
    type: 'days',
  },
  {
    id: 'saved_10000',
    title: 'Tu vaux de lâ€™or !',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(10000)} !`,
    icon: 'ðŸ†',
    requirement: 10000,
    type: 'money',
  },
  {
    id: 'units_1000',
    title: '1000 unitÃ©s !',
    description: 'Tu as Ã©vitÃ© 1000 unitÃ©s !',
    icon: 'ðŸ‹ï¸',
    requirement: 1000,
    type: 'units',
  },
  {
    id: 'days_730',
    title: 'Deux ans : lÃ©gendaire',
    description: 'Tu es sobre depuis 2 ans !',
    icon: 'ðŸ¤©',
    requirement: 730,
    type: 'days',
  },
  {
    id: 'days_1000',
    title: 'Niveau 1000',
    description: 'Tu es sobre depuis 1000 jours !',
    icon: 'ðŸŽ®',
    requirement: 1000,
    type: 'days',
  },
  {
    id: 'drinks_5000',
    title: 'Arbre de persÃ©vÃ©rance',
    description: 'Tu as Ã©vitÃ© 5000 verres !',
    icon: 'ðŸŒ³',
    requirement: 5000,
    type: 'drinks',
  },
  {
    id: 'days_1095',
    title: 'Trois ans de lumiÃ¨re',
    description: 'Tu es sobre depuis 3 ans !',
    icon: 'ðŸ’¡',
    requirement: 1095,
    type: 'days',
  },
  {
    id: 'saved_25000',
    title: 'Diamant taillÃ©',
    description: `Tu as Ã©conomisÃ© ${formatCurrency(25000)} !`,
    icon: 'ðŸ’Ž',
    requirement: 25000,
    type: 'money',
  },
  {
    id: 'units_2500',
    title: 'Ã€ ta santÃ© !',
    description: 'Tu as Ã©vitÃ© 2500 unitÃ©s !',
    icon: 'ðŸ¥‚',
    requirement: 2500,
    type: 'units',
  },
  {
    id: 'days_1825',
    title: 'Câ€™est quoi lâ€™alcool ?',
    description: 'Tu es sobre depuis 5 ans !',
    icon: 'â“',
    requirement: 1825,
    type: 'days',
  },
  {
    id: 'drinks_10000',
    title: 'Niveau extraterrestre',
    description: 'Tu as Ã©vitÃ© 10 000 verres !',
    icon: 'ðŸ›¸',
    requirement: 10000,
    type: 'drinks',
  },
  {
    id: 'units_5000',
    title: 'InarrÃªtable',
    description: 'Tu as Ã©vitÃ© 5000 unitÃ©s !',
    icon: 'ðŸ’ª',
    requirement: 5000,
    type: 'units',
  },
  {
    id: 'units_7500',
    title: 'Statut Ã©toile',
    description: 'Tu as Ã©vitÃ© 7500 unitÃ©s !',
    icon: 'â­ï¸',
    requirement: 7500,
    type: 'units',
  },
  {
    id: 'units_10000',
    title: 'Tu lâ€™as fait !',
    description: 'Tu as Ã©vitÃ© 10 000 unitÃ©s !',
    icon: 'ðŸ',
    requirement: 10000,
    type: 'units',
  },
];
export const getAchievementDefinitionsDE = (formatCurrency) => [
  {
    id: 'saved_1',
    title: 'Sparen beginnt',
    description: `Du hast ${formatCurrency(1)} gespart!`,
    icon: 'ðŸ‘›',
    requirement: 1,
    type: 'money',
  },
  {
    id: 'saved_10',
    title: 'Zehner drin!',
    description: `Du hast ${formatCurrency(10)} gespart!`,
    icon: 'ðŸ“ˆ',
    requirement: 10,
    type: 'money',
  },
  {
    id: 'units_1',
    title: 'Erste HÃ¼rde geschafft',
    description: 'Du hast 1 Einheit vermieden!',
    icon: 'ðŸ¥‡',
    requirement: 1,
    type: 'units',
  },
  {
    id: 'days_1',
    title: 'Die ersten 24 Stunden',
    description: 'Du bist 1 Tag alkoholfrei!',
    icon: '1ï¸âƒ£',
    requirement: 1,
    type: 'days',
  },
  {
    id: 'drinks_5',
    title: 'FÃ¼nf am StÃ¼ck',
    description: 'Du hast 5 GetrÃ¤nke vermieden!',
    icon: '5ï¸âƒ£',
    requirement: 5,
    type: 'drinks',
  },
  {
    id: 'saved_25',
    title: 'Es zÃ¤hlt langsam',
    description: `Du hast ${formatCurrency(25)} gespart!`,
    icon: 'ðŸ’°',
    requirement: 25,
    type: 'money',
  },
  {
    id: 'days_2',
    title: 'Nicht nachgegeben',
    description: 'Du bist 2 Tage alkoholfrei!',
    icon: 'ðŸ«',
    requirement: 2,
    type: 'days',
  },
  {
    id: 'saved_50',
    title: 'Der Stapel wÃ¤chst',
    description: `Du hast ${formatCurrency(50)} gespart!`,
    icon: 'ðŸ’¸',
    requirement: 50,
    type: 'money',
  },
  {
    id: 'days_5',
    title: 'Rhythmus gefunden',
    description: 'Du bist 5 Tage alkoholfrei!',
    icon: 'ðŸ–ï¸',
    requirement: 5,
    type: 'days',
  },

  {
    id: 'saved_100',
    title: 'Das summiert sich richtig',
    description: `Du hast ${formatCurrency(100)} gespart!`,
    icon: 'ðŸ’°',
    requirement: 100,
    type: 'money',
  },
  {
    id: 'drinks_25',
    title: 'LÃ¤uft bei dir',
    description: 'Du hast 25 GetrÃ¤nke vermieden!',
    icon: 'ðŸ’ª',
    requirement: 25,
    type: 'drinks',
  },
  {
    id: 'units_10',
    title: 'Zweistellig',
    description: 'Du hast 10 Einheiten vermieden!',
    icon: 'ðŸ˜',
    requirement: 10,
    type: 'units',
  },
  {
    id: 'days_7',
    title: 'Eine Woche geschafft',
    description: 'Du bist 1 Woche alkoholfrei!',
    icon: 'âœ…',
    requirement: 7,
    type: 'days',
  },
  {
    id: 'days_10',
    title: 'Zehn Tage!',
    description: 'Du bist 10 Tage alkoholfrei!',
    icon: 'ðŸ”Ÿ',
    requirement: 10,
    type: 'days',
  },
  {
    id: 'drinks_50',
    title: 'Was fÃ¼r ein Meilenstein',
    description: 'Du hast 50 GetrÃ¤nke vermieden!',
    icon: 'ðŸ†',
    requirement: 50,
    type: 'drinks',
  },
  {
    id: 'saved_250',
    title: 'Dranbleiben zahlt sich aus',
    description: `Du hast ${formatCurrency(250)} gespart!`,
    icon: 'ðŸ¤‘',
    requirement: 250,
    type: 'money',
  },
  {
    id: 'days_14',
    title: 'Du schaffst das!',
    description: 'Du bist 2 Wochen alkoholfrei!',
    icon: 'ðŸ˜Ž',
    requirement: 14,
    type: 'days',
  },
  {
    id: 'drinks_100',
    title: '100 Mal stÃ¤rker',
    description: 'Du hast 100 GetrÃ¤nke vermieden!',
    icon: 'ðŸ’¯',
    requirement: 100,
    type: 'drinks',
  },
  {
    id: 'days_21',
    title: 'Du holst dir dein Leben zurÃ¼ck',
    description: 'Du bist 3 Wochen alkoholfrei!',
    icon: 'â˜€ï¸',
    requirement: 21,
    type: 'days',
  },
  {
    id: 'saved_500',
    title: 'Nicht aufzuhalten',
    description: `Du hast ${formatCurrency(500)} gespart!`,
    icon: 'ðŸ›‘',
    requirement: 500,
    type: 'money',
  },
  {
    id: 'units_50',
    title: 'Das ist Konstanz!',
    description: 'Du hast 50 Einheiten vermieden!',
    icon: 'ðŸ‘',
    requirement: 50,
    type: 'units',
  },
  {
    id: 'days_30',
    title: 'Ein Monat Kontrolle',
    description: 'Du bist 1 Monat alkoholfrei!',
    icon: 'ðŸ—“ï¸',
    requirement: 30,
    type: 'days',
  },
  {
    id: 'drinks_200',
    title: 'Wie ein Zug unterwegs',
    description: 'Du hast 200 GetrÃ¤nke vermieden!',
    icon: 'ðŸš‚',
    requirement: 200,
    type: 'drinks',
  },
  {
    id: 'days_42',
    title: 'Sechs Wochen Momentum',
    description: 'Du bist 6 Wochen alkoholfrei!',
    icon: 'ðŸ˜',
    requirement: 42,
    type: 'days',
  },
  {
    id: 'saved_1000',
    title: 'Kein Kleingeld mehr',
    description: `Du hast ${formatCurrency(1000)} gespart!`,
    icon: 'ðŸ’¶',
    requirement: 1000,
    type: 'money',
  },
  {
    id: 'units_100',
    title: 'Du gewinnst!',
    description: 'Du hast 100 Einheiten vermieden!',
    icon: 'ðŸ',
    requirement: 100,
    type: 'units',
  },
  {
    id: 'drinks_300',
    title: 'Eisenstark',
    description: 'Du hast 300 GetrÃ¤nke vermieden!',
    icon: 'ðŸ§²',
    requirement: 300,
    type: 'drinks',
  },
  {
    id: 'days_60',
    title: 'Unzerbrechlich',
    description: 'Du bist 2 Monate alkoholfrei!',
    icon: 'ðŸ§±',
    requirement: 60,
    type: 'days',
  },
  {
    id: 'drinks_400',
    title: 'NÃ¤chstes Level',
    description: 'Du hast 400 GetrÃ¤nke vermieden!',
    icon: 'â­ï¸',
    requirement: 400,
    type: 'drinks',
  },
  {
    id: 'days_90',
    title: 'Du surfst weiter',
    description: 'Du bist 3 Monate alkoholfrei!',
    icon: 'ðŸŒŠ',
    requirement: 90,
    type: 'days',
  },
  {
    id: 'days_100',
    title: 'Bam, nÃ¤chster Schritt',
    description: 'Du bist 100 Tage alkoholfrei!',
    icon: 'ðŸ’£',
    requirement: 100,
    type: 'days',
  },
  {
    id: 'drinks_500',
    title: 'Du stehst wie ein Haus',
    description: 'Du hast 500 GetrÃ¤nke vermieden!',
    icon: 'ðŸ¡',
    requirement: 500,
    type: 'drinks',
  },
  {
    id: 'saved_2500',
    title: 'Finanzprofi',
    description: `Du hast ${formatCurrency(2500)} gespart!`,
    icon: 'ðŸ’²',
    requirement: 2500,
    type: 'money',
  },
  {
    id: 'units_250',
    title: 'On Fire',
    description: 'Du hast 250 Einheiten vermieden!',
    icon: 'ðŸ”¥',
    requirement: 250,
    type: 'units',
  },
  {
    id: 'days_150',
    title: 'Die Zeit arbeitet fÃ¼r dich',
    description: 'Du bist 150 Tage alkoholfrei!',
    icon: 'âŒš',
    requirement: 150,
    type: 'days',
  },
  {
    id: 'days_180',
    title: 'Halbes Jahr KÃ¶nig',
    description: 'Du bist 6 Monate alkoholfrei!',
    icon: 'ðŸ‘‘',
    requirement: 180,
    type: 'days',
  },
  {
    id: 'drinks_1000',
    title: 'Vulkanischer Erfolg',
    description: 'Du hast 1000 GetrÃ¤nke vermieden!',
    icon: 'ðŸŒ‹',
    requirement: 1000,
    type: 'drinks',
  },
  {
    id: 'days_250',
    title: 'Tiefe Wurzeln',
    description: 'Du bist 250 Tage alkoholfrei!',
    icon: 'ðŸŒ³',
    requirement: 250,
    type: 'days',
  },
  {
    id: 'saved_5000',
    title: 'Finanziell stabil',
    description: `Du hast ${formatCurrency(5000)} gespart!`,
    icon: 'ðŸ§',
    requirement: 5000,
    type: 'money',
  },
  {
    id: 'units_500',
    title: 'Waage der Disziplin',
    description: 'Du hast 500 Einheiten vermieden!',
    icon: 'âš–ï¸',
    requirement: 500,
    type: 'units',
  },
  {
    id: 'days_270',
    title: 'Wiedergeboren',
    description: 'Du bist 9 Monate alkoholfrei!',
    icon: 'ðŸ‘¶',
    requirement: 270,
    type: 'days',
  },
  {
    id: 'days_365',
    title: 'Ein Jahr geschafft',
    description: 'Du bist 1 Jahr alkoholfrei!',
    icon: 'ðŸŒŸ',
    requirement: 365,
    type: 'days',
  },
  {
    id: 'drinks_2000',
    title: 'Spitze des Eisbergs',
    description: 'Du hast 2000 GetrÃ¤nke vermieden!',
    icon: 'ðŸ—»',
    requirement: 2000,
    type: 'drinks',
  },
  {
    id: 'days_500',
    title: 'Pfadfinder',
    description: 'Du bist 500 Tage alkoholfrei!',
    icon: 'ðŸ—ºï¸',
    requirement: 500,
    type: 'days',
  },
  {
    id: 'saved_10000',
    title: 'Du bist Gold wert!',
    description: `Du hast ${formatCurrency(10000)} gespart!`,
    icon: 'ðŸ†',
    requirement: 10000,
    type: 'money',
  },
  {
    id: 'units_1000',
    title: '1000 Einheiten!',
    description: 'Du hast 1000 Einheiten vermieden!',
    icon: 'ðŸ‹ï¸',
    requirement: 1000,
    type: 'units',
  },
  {
    id: 'days_730',
    title: 'Zwei Jahre: legendÃ¤r',
    description: 'Du bist 2 Jahre alkoholfrei!',
    icon: 'ðŸ¤©',
    requirement: 730,
    type: 'days',
  },
  {
    id: 'days_1000',
    title: 'Level 1000',
    description: 'Du bist 1000 Tage alkoholfrei!',
    icon: 'ðŸŽ®',
    requirement: 1000,
    type: 'days',
  },
  {
    id: 'drinks_5000',
    title: 'Baum der Ausdauer',
    description: 'Du hast 5000 GetrÃ¤nke vermieden!',
    icon: 'ðŸŒ³',
    requirement: 5000,
    type: 'drinks',
  },
  {
    id: 'days_1095',
    title: 'Drei Jahre Licht',
    description: 'Du bist 3 Jahre alkoholfrei!',
    icon: 'ðŸ’¡',
    requirement: 1095,
    type: 'days',
  },
  {
    id: 'saved_25000',
    title: 'Geschliffener Diamant',
    description: `Du hast ${formatCurrency(25000)} gespart!`,
    icon: 'ðŸ’Ž',
    requirement: 25000,
    type: 'money',
  },
  {
    id: 'units_2500',
    title: 'Prost auf dich!',
    description: 'Du hast 2500 Einheiten vermieden!',
    icon: 'ðŸ¥‚',
    requirement: 2500,
    type: 'units',
  },
  {
    id: 'days_1825',
    title: 'Was ist Alkohol?',
    description: 'Du bist 5 Jahre alkoholfrei!',
    icon: 'â“',
    requirement: 1825,
    type: 'days',
  },
  {
    id: 'drinks_10000',
    title: 'AuÃŸerirdisches Level',
    description: 'Du hast 10.000 GetrÃ¤nke vermieden!',
    icon: 'ðŸ›¸',
    requirement: 10000,
    type: 'drinks',
  },
  {
    id: 'units_5000',
    title: 'Unaufhaltsam',
    description: 'Du hast 5000 Einheiten vermieden!',
    icon: 'ðŸ’ª',
    requirement: 5000,
    type: 'units',
  },
  {
    id: 'units_7500',
    title: 'Sternstatus',
    description: 'Du hast 7500 Einheiten vermieden!',
    icon: 'â­ï¸',
    requirement: 7500,
    type: 'units',
  },
  {
    id: 'units_10000',
    title: 'Du hast es geschafft!',
    description: 'Du hast 10.000 Einheiten vermieden!',
    icon: 'ðŸ',
    requirement: 10000,
    type: 'units',
  },
];
